// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SQLiteWebApi.Data;

#nullable disable

namespace SQLiteWebApi.Data.Migrations
{
    [DbContext(typeof(SQLiteWebApiDbContext))]
    [Migration("20230831221759_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("SQLiteWebApi.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppUser");

                    b.HasData(
                        new
                        {
                            Id = "e9e16361-afd8-4f48-ad45-9cb6ad51fb60",
                            CreatedDate = "2023-08-31 17:00:00",
                            Email = "tmax@email.com",
                            FirstName = "Tom",
                            LastName = "Max"
                        },
                        new
                        {
                            Id = "9214c650-818b-4066-bd9c-ae3f4669c2b7",
                            CreatedDate = "2023-08-31 17:00:00",
                            Email = "afay@email.com",
                            FirstName = "Ann",
                            LastName = "Fay"
                        },
                        new
                        {
                            Id = "7f5cf754-966d-4094-89d7-759daab61074",
                            CreatedDate = "2023-08-31 17:00:00",
                            Email = "jsun@email.com",
                            FirstName = "Joe",
                            LastName = "Sun"
                        },
                        new
                        {
                            Id = "204a8fbd-443b-42e0-9985-79164a78a85f",
                            CreatedDate = "2023-08-31 17:00:00",
                            Email = "sfox@email.com",
                            FirstName = "Sue",
                            LastName = "Fox"
                        },
                        new
                        {
                            Id = "17a95541-1e3d-4dc9-bea9-729da6dd67a3",
                            CreatedDate = "2023-08-31 17:00:00",
                            Email = "brey@email.com",
                            FirstName = "Ben",
                            LastName = "Ray"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
